const state={transcriptText:"",transcriptName:"",result:null,selectedIdea:null,chat:[],generatedDataUrl:"",selectedQuadrant:null,selectedDataUrl:""};
const $=id=>document.getElementById(id); const cfg=window.MOTION_DIRECTOR_CONFIG||{}; let backend=localStorage.getItem("motionDirectorBackend")||cfg.BACKEND_URL||"";
const apiUrl=path=>`${backend.replace(/\/$/,"")}${path}`; const show=el=>el.classList.remove("hidden"); const setStatus=(id,t)=>$(id).textContent=t;
const escapeHtml=(s="")=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function request(path,options={}){if(!backend&&location.hostname.endsWith("github.io"))throw new Error("Backend URL is not set. Click Backend settings and paste your deployed backend URL."); const r=await fetch(apiUrl(path),{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}); if(!r.ok){let d="";try{d=(await r.json()).error||""}catch{} throw new Error(d||`Request failed (${r.status})`)} return r}
function readTranscript(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=reject;reader.readAsText(file)})}
const dz=$("dropzone"); dz.addEventListener("click",()=>$("fileInput").click()); dz.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")$("fileInput").click()}); ["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("drag")})); ["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove("drag")})); dz.addEventListener("drop",e=>handleFile(e.dataTransfer.files[0])); $("fileInput").addEventListener("change",e=>handleFile(e.target.files[0]));
async function handleFile(file){if(!file)return; const ext=file.name.split(".").pop().toLowerCase(); if(!["srt","txt"].includes(ext))return alert("Please upload an SRT or TXT transcript."); if(file.size>2500000)return alert("V1 supports transcript files up to about 2.5 MB."); state.transcriptText=await readTranscript(file);state.transcriptName=file.name;$("fileMeta").textContent=`${file.name} · ${(file.size/1024).toFixed(1)} KB`;$("processBtn").disabled=false;setStatus("processStatus","Ready to process.")}
$("processBtn").addEventListener("click",async()=>{try{$("processBtn").disabled=true;setStatus("processStatus","Analyzing the whole transcript…");const r=await request("/api/process",{method:"POST",body:JSON.stringify({transcript:state.transcriptText,filename:state.transcriptName})});state.result=await r.json();renderIdeas();show($("ideasSection"));show($("studioSection"));$("ideasSection").scrollIntoView({behavior:"smooth"});setStatus("processStatus",`Found ${state.result.ideas.length} opportunities.`)}catch(err){setStatus("processStatus",err.message);alert(err.message)}finally{$("processBtn").disabled=false}});
function renderIdeas(){if(!state.result)return;$("episodeSummary").textContent=state.result.episode_summary||"";const f=$("priorityFilter").value;const ideas=state.result.ideas.filter(i=>f==="all"||i.priority===f);$("ideasGrid").innerHTML=ideas.map(i=>`<button class="idea-card ${state.selectedIdea?.idea_id===i.idea_id?'active':''}" data-id="${i.idea_id}"><div class="meta"><span>#${String(i.idea_id).padStart(2,"0")} · ${escapeHtml(i.start_time)}–${escapeHtml(i.end_time)}</span><span class="priority ${i.priority}">${i.priority.replace("_"," ").toUpperCase()}</span></div><h4>${escapeHtml(i.concept)}</h4><p>${escapeHtml(i.rationale)}</p></button>`).join("");document.querySelectorAll(".idea-card").forEach(b=>b.addEventListener("click",()=>selectIdea(Number(b.dataset.id))))}
$("priorityFilter").addEventListener("change",renderIdeas);
function detail(label,value){return `<div class="detail-item"><small>${escapeHtml(label)}</small><div>${escapeHtml(String(value||""))}</div></div>`}
function selectIdea(id){state.selectedIdea=state.result.ideas.find(i=>i.idea_id===id);state.chat=[];renderIdeas();$("studioTitle").textContent=`Idea ${String(id).padStart(2,"0")} — ${state.selectedIdea.concept}`;$("ideaDetail").innerHTML=`<div class="detail-list">${detail("Time",`${state.selectedIdea.start_time}–${state.selectedIdea.end_time}`)}${detail("Type",state.selectedIdea.graphic_type)}${detail("On-screen text",(state.selectedIdea.onscreen_text||[]).join(" / "))}${detail("Visual elements",(state.selectedIdea.visual_elements||[]).join(", "))}${detail("Layout",state.selectedIdea.layout)}${detail("Animation",state.selectedIdea.animation_recommendation)}${detail("AI footage",state.selectedIdea.ai_footage_recommendation)}</div>`;$("chatLog").innerHTML=`<div class="assistant-bubble">Idea selected. Tell me how you want to push the design, or generate the 2×2 panel now.</div>`;$("generateBtn").disabled=false;$("studioSection").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".chip").forEach(b=>b.addEventListener("click",()=>{$("chatInput").value=b.dataset.prompt;sendChat()})); $("sendChatBtn").addEventListener("click",sendChat);
async function sendChat(){if(!state.selectedIdea)return;const message=$("chatInput").value.trim();if(!message)return;state.chat.push({role:"user",content:message});appendBubble("user",message);$("chatInput").value="";try{const r=await request("/api/chat",{method:"POST",body:JSON.stringify({idea:state.selectedIdea,history:state.chat})});const d=await r.json();state.chat.push({role:"assistant",content:d.reply});appendBubble("assistant",d.reply)}catch(err){appendBubble("assistant",`Error: ${err.message}`)}}
function appendBubble(role,text){const d=document.createElement("div");d.className=role==="user"?"user-bubble":"assistant-bubble";d.textContent=text;$("chatLog").appendChild(d);$("chatLog").scrollTop=$("chatLog").scrollHeight}
$("generateBtn").addEventListener("click",async()=>{if(!state.selectedIdea)return;show($("designSection"));setStatus("generationStatus","Generating 4 directions…");$("designSection").scrollIntoView({behavior:"smooth"});try{const r=await request("/api/generate-image",{method:"POST",body:JSON.stringify({idea:state.selectedIdea,history:state.chat})});const d=await r.json();state.generatedDataUrl=`data:image/png;base64,${d.image_base64}`;$("generatedImage").src=state.generatedDataUrl;state.selectedQuadrant=null;state.selectedDataUrl="";$("packageBtn").disabled=true;document.querySelectorAll("#quadrantGrid button").forEach(b=>b.classList.remove("selected"));setStatus("generationStatus","Choose a panel.")}catch(err){setStatus("generationStatus",err.message)}});
document.querySelectorAll("#quadrantGrid button").forEach(btn=>btn.addEventListener("click",()=>selectQuadrant(Number(btn.dataset.q),btn)));
function selectQuadrant(q,btn){if(!state.generatedDataUrl)return;document.querySelectorAll("#quadrantGrid button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");state.selectedQuadrant=q;const img=new Image();img.onload=()=>{const sw=Math.floor(img.naturalWidth/2),sh=Math.floor(img.naturalHeight/2),sx=(q%2)*sw,sy=(q>1?1:0)*sh,c=$("selectedCanvas");c.width=sw;c.height=sh;c.getContext("2d").drawImage(img,sx,sy,sw,sh,0,0,sw,sh);state.selectedDataUrl=c.toDataURL("image/png");$("selectionLabel").textContent=["Top left","Top right","Bottom left","Bottom right"][q]+" selected.";$("packageBtn").disabled=false};img.src=state.generatedDataUrl}
$("packageBtn").addEventListener("click",async()=>{if(!state.selectedDataUrl)return;$("packageBtn").disabled=true;$("packageBtn").textContent="PACKAGING…";try{const r=await request("/api/package-ae",{method:"POST",body:JSON.stringify({idea:state.selectedIdea,quadrant:state.selectedQuadrant,selected_image_base64:state.selectedDataUrl.split(",")[1]})});const blob=await r.blob(),url=URL.createObjectURL(blob);$("downloadLink").href=url;$("downloadLink").download=`idea_${String(state.selectedIdea.idea_id).padStart(2,"0")}_AE_package.zip`;show($("downloadSection"));$("downloadSection").scrollIntoView({behavior:"smooth"})}catch(err){alert(err.message)}finally{$("packageBtn").disabled=false;$("packageBtn").textContent="PACKAGE FOR AFTER EFFECTS"}});
$("settingsBtn").addEventListener("click",()=>{$("backendInput").value=backend;$("settingsDialog").showModal()}); $("saveSettingsBtn").addEventListener("click",e=>{e.preventDefault();backend=$("backendInput").value.trim();localStorage.setItem("motionDirectorBackend",backend);$("settingsDialog").close()});
